spring:
  application:
    name: gatewayCompany
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        # 存栏微服务路径配置,其他微服务配置类似
        - id: pig-service-inventory
          #          uri: http://localhost:18081/ 避免写死,使用eureka 中服务的名字作为地址
          uri: lb://PIGSERVICEINVENTORY
          predicates:
            - Path=/api/inventory/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的factory
              args:
                #限流的键的解析器的 Bean 对象的名字。它使用 SpEL 表达式根据#{@beanName}从 Spring 容器中获取 Bean 对象
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1 #令牌桶每秒填充平均速率
                redis-rate-limiter.burstCapacity: 3 #令牌桶总容量

server:
  port: 8001
#eureka客户端配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
